# Site
title:              Brian Sinclair
bio:                'Climber. Cyclist. Homebrewer. Data Scientist.'
description:        "Think you can, and you''ll try. Believe you can, and you will"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/me.png'
background:         'assets/img/background.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
posts_page:         false
projects_page:      false
url:                http://www.sinclairbrian.com
# url:                http://localhost:4000
blog_url:           https://believeyoucanyouwill.wordpress.com/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   sinclairbrian

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        UA-51266637-2
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              sinclair.brian@gmail.com
twitter:            bpjsincl
facebook:           believeyoucanyouwill
github:             bpjsincl
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           sinclairbrian
#xing:              username
instagram:          bpjsincl
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
